run:
  deadline: 5m
  tests: true

linters-settings:
  govet:
    check-shadowing: true

  gofmt:
    simplify: true

  gci:
    sections:
    - standard
    - default
    - prefix(github.com/tsuru/nginx-operator)
    - blank
    - dot

issues:
  exclude-rules:
    # GCI does not handle well the kubebuilder annotations e.g. "// +kubebuilder:scaffold:imports".
    # Issue tracked at https://github.com/daixiang0/gci/issues/135.
    - path: main.go
      linters:
      - gci

linters:
  enable:
  - goimports
  - gofmt
  - misspell
  - govet
  - gci
  disable:
  - errcheck
